name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # 或者您想要触发工作流的分支名称

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 使用最新版的 Ubuntu 作为运行环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # 设置 Java 版本，根据您的项目需求调整
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd /home/runner/work/${{ github.repository }}/${{ github.repository }}
          mvn clean install

      - name: Copy JAR to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}  # 服务器地址
          username: ${{ secrets.SERVER_USER }}  # 服务器用户名
          key: ${{ secrets.SERVER_PRIVATE_KEY }}  # 服务器私钥
          source: 'target/*.jar'  # 指定要复制的 JAR 文件
          target: '/www/wwwroot'  # 服务器上的目标路径

      - name: Run deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            /www/server/java/jdk-17.0.8/bin/java -jar -Xmx1024M -Xms256M  
            /www/wwwroot/tradeplatform-0.0.1-SNAPSHOT.jar
            

